version: "3"

services:
  atproto-website:
    build:
      context: .
      dockerfile: Dockerfile
    image: atproto-website
    container_name: atproto-website
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
