version: '3'

services:
  next-js:
    build:
      context: .
      dockerfile: Dockerfile
    image: next-js
    container_name: next-js
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    environment:
      - NODE_ENV=development
      - PORT=3000
    networks:
      - next-js-network

networks:
  next-js-network:
    external: true
